// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IAnalysisController is an autogenerated mock type for the IAnalysisController type
type IAnalysisController struct {
	mock.Mock
}

// AnalysisHandler provides a mock function with given fields: ginCtx
func (_m *IAnalysisController) AnalysisHandler(ginCtx *gin.Context) {
	_m.Called(ginCtx)
}

// NewIAnalysisController creates a new instance of IAnalysisController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAnalysisController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAnalysisController {
	mock := &IAnalysisController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
